[colors.primary]
background = "0x1f1f28"
foreground = "0xdcd7ba"

[colors.normal]
black = "0x090618"
red = "0xc34043"
green = "0x76946a"
yellow = "0xc0a36e"
blue = "0x7e9cd8"
magenta = "0x957fb8"
cyan = "0x6a9589"
white = "0xc8c093"

[colors.bright]
black = "0x727169"
red = "0xe82424"
green = "0x98bb6c"
yellow = "0xe6c384"
blue = "0x7fb4ca"
magenta = "0x938aa9"
cyan = "0x7aa89f"
white = "0xdcd7ba"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[[colors.indexed_colors]]
index = 16
color = "0xffa066"

[[colors.indexed_colors]]
index = 17
color = "0xff5d62"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JuliaMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JuliaMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JuliaMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JuliaMono Nerd Font Mono"
style = "Regular"

[scrolling]
history = 5000

[window]
title = "Terminal"

[window.padding]
x = 20
y = 12
