return {
	"catppuccin/nvim",
	name = "catppuccin",
	config = function()
		require("catppuccin").setup({
			background = {
				light = "latte",
				dark = "mocha",
			},
			color_overrides = {
				latte = {
					rosewater = "#d73a49",
					flamingo = "#d73a49",
					red = "#d73a49",
					maroon = "#d73a49",
					pink = "#bf3989",
					mauve = "#6f42c1",
					peach = "#e36209",
					yellow = "#9a6700",
					green = "#22863a",
					teal = "#1b7c83",
					sky = "#1b7c83",
					sapphire = "#1b7c83",
					blue = "#005cc5",
					lavender = "#005cc5",
					text = "#24292e",
					subtext1 = "#24292f",
					subtext0 = "#32383f",
					overlay2 = "#424a53",
					overlay1 = "#57606a",
					overlay0 = "#6e7781",
					surface2 = "#8c8c8c",
					surface1 = "#d1d1d1",
					surface0 = "#e6e6e6",
					base = "#FFFFFF",
					mantle = "#f2f2f2",
					crust = "#ebebeb",
				},
				mocha = {
					rosewater = "#f97583",
					flamingo = "#f97583",
					red = "#f97583",
					maroon = "#f97583",
					pink = "#f778ba",
					mauve = "#b392f0",
					peach = "#ffab70",
					yellow = "#d29922",
					green = "#85e89d",
					teal = "#76e3ea",
					sky = "#76e3ea",
					sapphire = "#76e3ea",
					blue = "#79b8ff",
					lavender = "#79b8ff",
					text = "#e1e4e8",
					subtext1 = "#f4f4f4",
					subtext0 = "#f0f6fc",
					overlay2 = "#c9d1d9",
					overlay1 = "#b1bac4",
					overlay0 = "#8b949e",
					surface2 = "#6e7681",
					surface1 = "#484f58",
					surface0 = "#262b33",
					base = "#0d1117",
					mantle = "#0a0d12",
					crust = "#000000",
				},
			},
			transparent_background = false,
			show_end_of_buffer = false,
			custom_highlights = function(colors)
				return {
					CmpItemKindClass = { fg = colors.yellow },
					CmpItemKindColor = { fg = colors.red },
					CmpItemKindConstant = { fg = colors.yellow },
					CmpItemKindConstructor = { fg = colors.mauve },
					CmpItemKindCopilot = { fg = colors.teal },
					CmpItemKindEnum = { fg = colors.peach },
					CmpItemKindEnumMember = { fg = colors.blue },
					CmpItemKindEvent = { fg = colors.blue },
					CmpItemKindField = { fg = colors.peach },
					CmpItemKindFile = { fg = colors.blue },
					CmpItemKindFolder = { fg = colors.blue },
					CmpItemKindFunction = { fg = colors.mauve },
					CmpItemKindInterface = { fg = colors.peach },
					CmpItemKindKeyword = { fg = colors.red },
					CmpItemKindMethod = { fg = colors.mauve },
					CmpItemKindModule = { fg = colors.blue },
					CmpItemKindOperator = { fg = colors.blue },
					CmpItemKindProperty = { fg = colors.peach },
					CmpItemKindReference = { fg = colors.red },
					CmpItemKindSnippet = { fg = colors.blue },
					CmpItemKindStruct = { fg = colors.peach },
					CmpItemKindText = { fg = colors.green },
					CmpItemKindTypeParameter = { fg = colors.blue },
					CmpItemKindUnit = { fg = colors.green },
					CmpItemKindValue = { fg = colors.peach },
					CmpItemKindVariable = { fg = colors.peach },
					CmpItemMenu = { fg = colors.surface2 },
					CursorLineNr = { fg = colors.mauve, style = { "bold" } },
					FloatBorder = { bg = colors.base, fg = colors.surface0 },
					LineNr = { fg = colors.surface1 },
					LspInfoBorder = { link = "FloatBorder" },
					NormalFloat = { bg = colors.base },
					NullLsInfoBorder = { link = "FloatBorder" },
					Pmenu = { bg = colors.mantle, fg = "" },
					PmenuSel = { bg = colors.surface0, fg = "" },
					TelescopePreviewBorder = { bg = colors.crust, fg = colors.crust },
					TelescopePreviewNormal = { bg = colors.crust },
					TelescopePreviewTitle = { fg = colors.crust, bg = colors.crust },
					TelescopePromptBorder = { bg = colors.surface0, fg = colors.surface0 },
					TelescopePromptCounter = { fg = colors.mauve, style = { "bold" } },
					TelescopePromptNormal = { bg = colors.surface0 },
					TelescopePromptPrefix = { bg = colors.surface0 },
					TelescopePromptTitle = { fg = colors.surface0, bg = colors.surface0 },
					TelescopeResultsBorder = { bg = colors.mantle, fg = colors.mantle },
					TelescopeResultsNormal = { bg = colors.mantle },
					TelescopeResultsTitle = { fg = colors.mantle, bg = colors.mantle },
					TelescopeSelection = { bg = colors.surface0 },
					VertSplit = { bg = colors.base, fg = colors.surface0 },
					YankHighlight = { bg = colors.surface2 },
				}
			end,
		})

		vim.api.nvim_command("colorscheme catppuccin")
	end,
}
